name:                ottawa-brahms-choir
version:             0.1.0.0
github:              "isovector/ottawa-brahms-choir"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2018 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/isovector/ottawa-brahms-choir#readme>

dependencies:
- base >= 4.7 && < 5
- sitepipe
- lens
- lens-aeson
- string-conv
- text
- time
- strptime
- aeson

executables:
  ottawa-brahms-choir:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
